#pragma once

// This file is autogenerated from 'font_icons' directory.
// Do not edit manually.

#include "helpers/utf8.h"

#define ICON_AM_ABOUT_BOX U8("\xf900")
#define ICON_AM_ADD_LINK U8("\xf901")
#define ICON_AM_ALL U8("\xf902")
#define ICON_AM_BUILD_SOLUTION U8("\xf903")
#define ICON_AM_BUILD_SOLUTION_AS U8("\xf904")
#define ICON_AM_CANCEL U8("\xf905")
#define ICON_AM_COLOR_PALETTE U8("\xf906")
#define ICON_AM_DELETE U8("\xf907")
#define ICON_AM_DELETE_FOLDER U8("\xf908")
#define ICON_AM_FOLDER_BOTTOM_PANEL U8("\xf909")
#define ICON_AM_HISTOGRAM_VISUALIZER U8("\xf90a")
#define ICON_AM_LINKED_FOLDER_OPENED U8("\xf90b")
#define ICON_AM_OPEN U8("\xf90c")
#define ICON_AM_PERFORMANCE_REPORT U8("\xf90d")
#define ICON_AM_QUESTION_MARK U8("\xf90e")
#define ICON_AM_REFRESH U8("\xf90f")
#define ICON_AM_REMOVE_LINK U8("\xf910")
#define ICON_AM_RENAME U8("\xf911")
#define ICON_AM_REPORT U8("\xf912")
#define ICON_AM_SAVE U8("\xf913")
#define ICON_AM_SHAPE U8("\xf914")